POST http://localhost:3001/api/user/verify HTTP/1.1
content-type: application/json

{
	"email": "srettig@purdue.edu"
}

###

PATCH  http://localhost:3001/api/user/verify HTTP/1.1
content-type: application/json

{
	"email": "srettig@purdue.edu",
    "verifyId": "e78b213272d3405040ab01d91ddd0bbd2f9a571e67df1da8",
    "verifyCode": "084369"
}

###

POST  http://localhost:3001/api/user/signup HTTP/1.1
content-type: application/json

{
	"email": "srettig@purdue.edu",
    "verifyId": "e78b213272d3405040ab01d91ddd0bbd2f9a571e67df1da8",
    "userName": "sean",
    "password": "password",
    "displayName": "seanDisplay"
}

###