### Create user before this

POST http://localhost:3001/api/posts/ HTTP/1.1
content-type: application/json

{
    "content": "test-content",
    "is_event": "false",
    "userId": "59d0b9cb-99c7-4044-831a-743be7ca2028"
}

###

GET http://localhost:3001/api/posts/6708e4a24c38f807f7d9937a

###

DELETE  http://localhost:3001/api/posts/6708e4a24c38f807f7d9937a

###

GET http://localhost:3001/api/posts/6708e4a24c38f807f7d9937a